config/routes.rb
Onboard::Application.routes.draw do
  
  
  get "auth/:provider/callback" => "social_logins#create"

  resources :rooms do
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :show]

  resources :users

  resource :session

  root "rooms#index"

end

app/models/room.rb
class Room < ActiveRecord::Base

	# add relationships between other models
	belongs_to :user
	has_many :orders


	# validate certain things
	validates :name, presence: true
	validates :address, presence: true
	validates :price_in_pence, presence: true, numericality: { greater_than: 50 }



	# geocoder setup
	geocoded_by :address
	after_validation :geocode



	# add image attachment
	# in my styles i can use..
	# 720x240 -> either 720 wide or 240 high
	# 720x    -> 720 wide and however tall
	# x240     -> however wide and 240px tall
	# 720x240# -> crop to 720 by 240
	has_attached_file :image, styles: { large: "720x240#",
		medium: "240x240#", thumbnail: "60x60#" }

	# Paperclip wants you to check if its an image
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	# i want to make sure that we're logged in
	# on the new, create, edit, update and destroy
	# so before each one runs, do something to check
	before_action :make_sure_logged_in, 
	only: [:new, :create, :edit, :update, :destroy]


	def index
		# show a list of all the room
		@rooms = Room.all
	end

	def show
		# individual room page
		# params[:id] is that number at end of url
		@room = Room.find(params[:id])
	end

	def new
		# add a new room form
		# @room = Room.new
		@room = current_user.rooms.new
	end

	def create
		# enter the room into the database
		# @room = Room.new(room_params)
		@room = current_user.rooms.new(room_params)

		if @room.save
			flash[:success] = "Your room has been added"
			redirect_to room_path(@room)
		else
			render "new"
		end

	end

	def edit
		# edit form
		# @room = Room.find(params[:id])
		@room = current_user.rooms.find(params[:id])
	end

	def update
		# actually update the db
		# @room = Room.find(params[:id])
		@room = current_user.rooms.find(params[:id])

		if @room.update(room_params) #see below def room_params - save repeating
			flash[:success] = "Your room has been updated"
			redirect_to room_path(@room)
		else
			render "edit"
		end

	end

	def destroy
		# actually delete from the db
		# @room = Room.find(params[:id])
		@room = current_user.rooms.find(params[:id])

		@room.destroy
		flash[:success] = "Your room has been deleted"
		redirect_to root_path
	end


	def room_params
		# this whitelists our form data
		params.require(:room).permit(:name, :address, :number_of_beds,
			:price_in_pence, :is_available, :image)

	end


end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>

	<%= form.input :name %>
	<%= form.input :address %>
	<%= form.input :number_of_beds %>
	<%= form.input :price_in_pence %>
	<%= form.input :is_available %>
	<%= form.input :image %>

	<%= form.button :submit %>
	


<% end %>

app/views/rooms/edit.html.erb
<h2>Edit this room</h2>

<%= render "form" %>

app/views/rooms/index.html.erb
<h2>Rooms available</h2>

<% @rooms.each do |room| %>

	<div>



		<h3>
			<% if room.image? %>
				<%= image_tag room.image(:thumbnail) %>
			<% end %>
			
			<%= link_to room.name, room_path(room) %>
			<!-- dont need @ infront of room as we are inside the loop -->
		</h3>
	</div>

<% end %>

<p>
	<%= link_to "Add a new room", new_room_path, class: "button" %>
</p>

app/views/rooms/new.html.erb
<h2>Add a new room</h2>

<%= render "form" %>

app/views/rooms/show.html.erb
<p>
	<%= image_tag @room.image(:large) %>

	<!-- this maybe necessary for pdf as opposed to images -->
	<%= link_to "Download", @room.image.url %>
</p>





<h2>
	<%= @room.name %>
</h2>

<%= simple_format @room.address %>


<p>
	There are <%= pluralize @room.number_of_beds, "bed" %>
</p>

<p>
	<%= @room.price_in_pence %> pence
</p>

<% if @room.user.present? %>
	<p>
		This room was posted by <%= @room.user.username %>
	</p>

<% end %>


<% if logged_in? and current_user == @room.user %>

<p>
	<%= link_to "Edit this room", edit_room_path(@room), class: "button" %>

	<%= link_to "Delete this room", room_path(@room), method: :delete,
	class: "button", confirm: "Are you sure?" %>
</p>

<% else %>

<p>
	<%= link_to "Book this room", new_room_order_path(@room),
		class: "button" %>
</p>

<% end %>