config/routes.rb
Onboard::Application.routes.draw do
  
  
  get "auth/:provider/callback" => "social_logins#create"

  resources :rooms do
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :show]

  resources :users

  resource :session

  root "rooms#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">

      <div class="large-3 columns">
        <h1>
          <%= link_to "Onboard", root_path %>
        </h1>

        <ul class="side-nav">

          <% if logged_in? %>
            <li><%= current_user.name %></li>
            <li><%= link_to "Add a room", new_room_path %></li>
            <li>
                <%= link_to "Log out", session_path, method: :delete %>
            </li>

          <% else %>

            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Log in", new_session_path %></li>


          <% end %>



        </ul>



      </div>  

      <div class="large-9 columns">

        <% if flash[:success].present? %>
          <div data-alert class="alert-box success">
            <%= flash[:success] %>
           </div> 

        <% end %>

        <% if flash[:error].present? %>
          <div data-alert class="alert-box warning">
            <%= flash[:error] %>
           </div> 

        <% end %>

        <%= yield %>
      </div> 

     </div> 

  </body>
</html>